# Values to be changed

DEBUG_VISUALIZATION = True
CROP_VALUE_FROM_TOP = 230
DURATION_PER_FRAME_MAIN_MS = 20
RESIZED_FRAME_SIZE = (640, 480)
VISUALIZE_HARRIS = True
VISUALIZE_HARRIS_CLUSTERS = False
VISUALIZE_HOUGH = True
HOUGH_LINES_VERTICAL_THRESHOLD = 5
CLUSTER_HARRIS_HORIZONTAL_RELEVANCE = 1.5
